name: cs225-hw
version: 1.0

default-extensions: ScopedTypeVariables
ghc-options: -Wall -Wno-orphans -Wno-partial-type-signatures -j

library:
  source-dirs: src
  dependencies: 
    - base 
    - directory
    - template-haskell
    - text
    - uvmhs
